# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog von ccaspers
email: mail@ccaspers.com
description: > # this means to ignore newlines until "baseurl:"
  Dies, das, gesammelte Werke.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://caspers.xyz" # the base hostname & protocol for your site
twitter_username: _ccaspers
github_username:  ccaspers

# Build settings
markdown: kramdown

repository: ccaspers/ccaspers.github.io
